services:
  db:
    image: postgres:17-alpine
    container_name: postgres_booking-app
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
