INSERT INTO amenities (id, name, category_id)
VALUES
    (1, 'Free Wi-Fi', 1),
    (2, 'Air Conditioning/Heating', 1),
    (3, 'Television', 2),
    (4, 'Bathroom Essentials', 1),
    (5, 'Bed Linens', 1),
    (6, 'Room Service', 2),
    (7, '24-Hour Reception', 2),
    (8, 'Parking', 2),
    (9, 'Laundry Facilities', 2),
    (10, 'Mini-Bar', 2),
    (11, 'Iron and Ironing Board', 2),
    (12, 'Wake-up Service', 2),
    (13, 'Complimentary Breakfast', 3),
    (14, 'On-Site Restaurant or Café', 3),
    (15, 'Bar or Lounge', 3),
    (16, 'Coffee Maker', 3),
    (17, 'Swimming Pool', 4),
    (18, 'Fitness Center', 4),
    (19, 'Spa Services', 4),
    (20, 'Business Center', 4),
    (21, 'Game Room', 4),
    (22, 'Babysitting Services', 5),
    (23, 'Kids'' Play Area', 5),
    (24, 'Cribs/High Chairs', 5),
    (25, 'Kids'' Menu', 5),
    (26, 'Wheelchair Accessible Rooms', 6),
    (27, 'Elevator Access', 6),
    (28, 'Visual and Hearing Impairment Support', 6),
    (29, 'Energy-Efficient Lighting', 7),
    (30, 'Sustainable Toiletries', 7),
    (31, 'Bicycle Rentals', 7),
    (32, 'Green Cleaning Products', 7),
    (33, 'Smart TVs', 8),
    (34, 'Charging Stations', 8),
    (35, 'Keyless Entry', 8),
    (36, 'Welcome Gifts', 9),
    (37, 'Pet-Friendly Rooms', 9),
    (38, 'Local Tours & Activities', 9),
    (39, 'Concierge Service', 9),
    (40, 'Safe Deposit Box', 10),
    (41, 'Smoke Detectors', 10),
    (42, '24/7 Security', 10);
